version: '3'

services:
  db:
    build: ./db
    image: danone-hw-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5434:5432'
    volumes:
      - ${DATA_PATH_HOST}/postgres/db-data:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: ./app/compose/local/Dockerfile
    image: danone-hw-app
    ports:
      - '3000:${APP_SERVER_PORT:-3000}'
    env_file: ./.env
    volumes:
      - ./app:/app:rw
      - node_modules:/app/node_modules
    depends_on:
      - db
    links:
      - db
    command:
      [
        './wait-for-db.sh',
        'db:5432',
        '--',
        'pm2-runtime',
        'start',
        'ecosystem.config.js',
      ]
    stdin_open: true
    tty: true

volumes:
  db-config:
  db-log:
  db-data:
  node_modules:
